apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: nbuyi88ss-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/nbuyi88ss-java-quarkus-gitops